baseURL = 'https://docs.fensak.io/'
title = 'Fensak Docs'

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[module]
proxy = "direct"
[[module.imports]]
  path = "github.com/google/docsy"
[[module.imports]]
  path = "github.com/google/docsy/dependencies"

[languages]
[languages.en]
title = 'Fensak Docs'
description = 'Documentation for the Fensak service, including configuration, rules scripts, and user docs.'
languageName = 'English'
weight = 1

[menu]
[[menu.main]]
  name = "fensak.io"
  weight = 1
  url = "https://fensak.io"
[[menu.main]]
  name = "Blog"
  weight = 49
  url = "https://blog.fensak.io"
[[menu.main]]
  name = "Community"
  weight = 50
  url = "https://github.com/orgs/fensak-io/discussions"

[params]
copyright = "Fensak, LLC"
privacy_policy = "/policies/privacy/"

github_repo = "https://github.com/fensak-io/docs-and-policies"
github_project_repo = "https://github.com/fensak-io/fensak"

[params.ui]
navbar_translucent_over_cover_disable = true
breadcrumb_disable = true
sidebar_menu_compact = false

[params.links]
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/fensak-io"
  icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
  name = "Discussions"
  url = "https://github.com/orgs/fensak-io/discussions"
  icon = "fa fa-comments"
  desc = "Discuss development issues around the project"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "github"
      guessSyntax = true
